server:
  port: 8080

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: git@github.com:manvendra/configurations.git
          passphrase: mpsingh
          search-paths: '*service'

management:
  endpoints:
    web:
      exposure:
        include: "*"